<?php

namespace Louvre\ReservationBundle\Repository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findTotalTickets($selectedDate)
    {
        $query = $this->createQueryBuilder('t')
            ->where('t.date = :date')
            ->setParameter('date', $selectedDate)
            ->select('SUM(t.numeroTickets)')
            ->getQuery()
        ;

        return $query->getSingleScalarResult();
    }
}
