louvre_reservation:
    resource: "@LouvreReservationBundle/Controller/ReservationController.php"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
